../src/top_id.py E021.predict ./evl.idx >E021.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E021.top1.idx > E021.top1.list
../src/top_id.py E022.predict ./evl.idx >E022.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E022.top1.idx > E022.top1.list
../src/top_id.py E023.predict ./evl.idx >E023.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E023.top1.idx > E023.top1.list
../src/top_id.py E024.predict ./evl.idx >E024.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E024.top1.idx > E024.top1.list
../src/top_id.py E025.predict ./evl.idx >E025.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E025.top1.idx > E025.top1.list
../src/top_id.py E026.predict ./evl.idx >E026.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E026.top1.idx > E026.top1.list
../src/top_id.py E027.predict ./evl.idx >E027.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E027.top1.idx > E027.top1.list
../src/top_id.py E028.predict ./evl.idx >E028.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E028.top1.idx > E028.top1.list
../src/top_id.py E029.predict ./evl.idx >E029.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E029.top1.idx > E029.top1.list
../src/top_id.py E030.predict ./evl.idx >E030.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E030.top1.idx > E030.top1.list
../src/top_id.py E031.predict ./evl.idx >E031.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E031.top1.idx > E031.top1.list
../src/top_id.py E032.predict ./evl.idx >E032.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E032.top1.idx > E032.top1.list
../src/top_id.py E033.predict ./evl.idx >E033.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E033.top1.idx > E033.top1.list
../src/top_id.py E034.predict ./evl.idx >E034.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E034.top1.idx > E034.top1.list
../src/top_id.py E035.predict ./evl.idx >E035.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E035.top1.idx > E035.top1.list
../src/top_id.py E036.predict ./evl.idx >E036.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E036.top1.idx > E036.top1.list
../src/top_id.py E037.predict ./evl.idx >E037.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E037.top1.idx > E037.top1.list
../src/top_id.py E038.predict ./evl.idx >E038.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E038.top1.idx > E038.top1.list
../src/top_id.py E039.predict ./evl.idx >E039.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E039.top1.idx > E039.top1.list
../src/top_id.py E040.predict ./evl.idx >E040.top1.idx && perl /data/MM2/MED/labelsets/select_files.pl /data/MM2/MED/labelsets/filelists/imtraj_nospfv.list E040.top1.idx > E040.top1.list
